CREATE DATABASE customer_behavior;
select * from customer;

-- What is total revenue generated by female vs male customers?
select gender, sum(purchase_amount) as Revenue from customer group by gender;

-- which customers used a discount bbut still spent more than average purchase amount?
select customer_id, purchase_amount from customer where discount_applied = 'Yes' and (purchase_amount) >= (select avg(purchase_amount) from customer);

-- which are the top 5 products with the highest avergae review rating
select item_purchased, round(avg(review_rating),2) as ReviewRating from customer group by item_purchased order by avg(review_rating) desc limit 5;

-- Compare the average purchase amounts betwween Standard and Express shipping
select shipping_type, round(avg(purchase_amount),2) from customer where shipping_type in ( 'Standard','Express') group by shipping_type;

-- Do subscribed customers spend more ? compare average spend and total revenue between subcribers and non subcribers
select subscription_status, count(customer_id) as total_customer, avg(purchase_amount) as avg_spend, sum(purchase_amount) as total_revenue
from customer group by subscription_status 
order by avg_spend, total_revenue desc ;

-- Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, 
round(100 * sum(case when discount_applied='Yes' then 1 else 0 end)/ count(*),2) as discount_rate from customer 
group by item_purchased
order by discount_rate desc
limit 5;

-- Segment customers into new, returnng and royal based on their total number of previous purchases nad show count of each segment
with customer_type as
(
select customer_id, previous_purchases,
case 
	when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
end as customer_segments
from customer
)
select customer_segments, count(*) as 'number of purchases' from customer_type group by customer_segments;

-- What are the top 3 most purchased amount within each category?
with item_counts as
(
select category, item_purchased, count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders from item_counts where item_rank <=3;

-- Are customers who are repeat buyers (more than 5 previous purchase) are more likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers from customer 
where previous_purchases > 5
group by subscription_status;

-- What is revenue status of each age group
select age_group, sum(purchase_amount) as total from customer group by age_group order by total desc ;